"""initial

Revision ID: 3690125d36a9
Revises: 
Create Date: 2026-07-27 11:10:32.691126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3690125d36a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False, comment='任务类型，如 ai.classify_document'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块'),
    sa.Column('source_file_id', sa.String(length=36), nullable=True, comment='源文件 ID'),
    sa.Column('source_ocr_job_id', sa.String(length=36), nullable=True, comment='源 OCR 任务 ID'),
    sa.Column('prompt_key', sa.String(length=100), nullable=True, comment='使用的 prompt 标识'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True, comment='AI 结构化结果'),
    sa.Column('raw_response', sa.Text(), nullable=True, comment='AI 原始响应'),
    sa.Column('confidence', sa.String(length=20), nullable=True, comment='置信度'),
    sa.Column('warnings', sa.JSON(), nullable=True, comment='警告列表'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型，如 confirm/archive/delete'),
    sa.Column('resource_type', sa.String(length=100), nullable=False, comment='资源类型，如 archive_document'),
    sa.Column('resource_id', sa.String(length=36), nullable=False, comment='资源 ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='操作者 ID'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='操作者名称'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='额外数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='存储文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME 类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小 (bytes)'),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False, comment='上传者 ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False, comment='任务类型，如 ocr.extract_receipt'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块，如 tommy'),
    sa.Column('source_file_id', sa.String(length=36), nullable=False, comment='源文件 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/running/succeeded/failed/needs_review'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='OCR 识别原文'),
    sa.Column('confidence', sa.String(length=20), nullable=True, comment='置信度: low/medium/high'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='处理耗时（秒）'),
    sa.Column('created_by', sa.String(length=36), nullable=False, comment='创建者 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('tommy_rental_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False, comment='物业名称'),
    sa.Column('unit_number', sa.String(length=50), nullable=False, comment='单位编号，如 A座8樓B室 / 车位01'),
    sa.Column('unit_type', sa.String(length=20), nullable=False, comment='类型: 住宅/車位'),
    sa.Column('tenant_name', sa.String(length=100), nullable=True, comment='当前租户名称'),
    sa.Column('tenant_email', sa.String(length=255), nullable=True, comment='租户电邮'),
    sa.Column('lease_start', sa.Date(), nullable=True, comment='当前租约开始日期'),
    sa.Column('lease_end', sa.Date(), nullable=True, comment='当前租约结束日期'),
    sa.Column('monthly_rent', sa.Numeric(precision=12, scale=2), nullable=True, comment='当前月租金 (HK$)'),
    sa.Column('is_occupied', sa.Boolean(), nullable=True, comment='是否已出租'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active/expiring/expired/vacant'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions_view',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('permission_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tommy_archive_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_file_id', sa.String(length=36), nullable=False, comment='原始文件 ID'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='建议分类: 財務/人事/租務/教育局通告/會議/其他'),
    sa.Column('suggested_name', sa.String(length=255), nullable=True, comment='建议新文件名'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='提取金额'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='到期日'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='OCR 识别原文'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI 摘要'),
    sa.Column('confidence', sa.String(length=20), nullable=True, comment='AI 置信度: low/medium/high'),
    sa.Column('source_file_id', sa.String(length=36), nullable=True, comment='来源文件 ID（归档后）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('retry_count', sa.String(length=5), nullable=True, comment='OCR/AI 重试次数'),
    sa.Column('last_reviewed_by', sa.String(length=36), nullable=True, comment='最后复核人'),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True, comment='最后复核时间'),
    sa.Column('created_by', sa.String(length=36), nullable=False, comment='创建者 ID'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='更新者 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['original_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tommy_rental_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False, comment='单位 ID'),
    sa.Column('tenant_name', sa.String(length=100), nullable=False, comment='租户名称'),
    sa.Column('lease_start', sa.Date(), nullable=False, comment='租约开始日期'),
    sa.Column('lease_end', sa.Date(), nullable=False, comment='租约结束日期'),
    sa.Column('monthly_rent', sa.Numeric(precision=12, scale=2), nullable=False, comment='月租金 (HK$)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active/expired/terminated'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['tommy_rental_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tommy_rental_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False, comment='单位 ID'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='应缴金额 (HK$)'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='缴费截止日'),
    sa.Column('paid_date', sa.Date(), nullable=True, comment='实际缴费日期'),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='实际缴费金额'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/paid/overdue/partial'),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True, comment='是否已发送缴费提醒'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['tommy_rental_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles_view',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles_view')
    op.drop_table('user_roles')
    op.drop_table('tommy_rental_payments')
    op.drop_table('tommy_rental_leases')
    op.drop_table('tommy_archive_documents')
    op.drop_table('role_permissions_view')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('tommy_rental_units')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('ocr_jobs')
    op.drop_table('files')
    op.drop_table('audit_logs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
